### ISSUE TITLE
Blogpost: Example of every city what can be improved

### ISSUE THREAD

**Issue by DylanVanAssche** [oSoc18/SmartFlanders#65]
# Task

- [x] Mechelen: public toilets
- [ ] Ghent: A lot of data, difficult to keep it up to date (some is already LD)
- [ ] Roeselare: partners with HogeNood app to find public toilets for wheelchair people. No public data or API available.
- [ ] Kortrijk: a lot of data
- [x] Leuven: no public data portal
- [ ] Hasselt: no data found, only some data on their website like: https://www.hasselt.be/nl/search/results/data (PMD, garbage, ... data)
- [ ] Turnhout: data dump, not public available. Some data like garbage collecting is available on their website
- [ ] Antwerp: a lot of data, not linked
- [ ] Brugge: a lot of data not linked + HogeNood
- [ ] Aalst: datadump, nice structure but no public data
- [ ] Sint-Niklaas: nice portal but not easy to get the data and not linked
- [x] Genk: no data found, they publish some databases but only in their bib (https://www.bibliotheekgenk.be/databanken)
- [ ] Oostende: a lot of data, mostly in unreadable PDF's. Accessibility is published using ToeVla (https://www.oostende.be/product.aspx?id=17758)

https://docs.google.com/spreadsheets/d/1kdePLS4IxPGn5KltB9Sw_uTEivZrN4xM2v7RPxnJmFI/edit#gid=0

TARGET: every day publish 1 example

# Version
- SmartFlanders: V
- NodeJS: 8.13 LTS
